In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print("1_Dimentional data",arr1,sep='\n',end ='\n\n')

arr2 = np.array([[1,2,3,4,5,6],[1,2,1,1,2,1]])
print("2_Dimentional data ",arr1,sep='\n',end ='\n\n')

arr3 = np.array([[1,2,3,4,5,6],[1,2,1,1,2,1],[1,2,1,1,2,1]])
print("3_Dimentional data or multi dimentional",arr1,sep='\n',end ='\n\n')

print(arr1.ndim)

1_Dimentional data
[1 2 3 4 5 6]

2_Dimentional data 
[1 2 3 4 5 6]

3_Dimentional data or multi dimentional
[1 2 3 4 5 6]

1


In [ ]:
z = np.zeros((4,4))
o = np.ones((4,4))
i = np.eye(4)
f = np.full((4,4),"vamsi")
r = np.arange(0,11,2)
l = np.linspace(1,50,3)
#np.random.seed()
ra = np.random.randint(10,200000)
ra_f = np.random.rand(5,5)
ra_m = np.random.randint(1,50,(2,2))
ra_choice = np.random.choice(["vamsi","ramya","jaya","srinu"],2)
reshape = arr3.reshape(6,3)
flatten = arr3.flatten()
trnasform = arr3.T


print(z,end='\n\n')
print(i,end='\n\n')
print(f,end='\n\n')
print(o,end='\n\n')
print("Array of Even numbers : ",r,end='\n\n')
print("Array of 2 parts : ",l,end='\n\n')
print("Array of random number : ",ra,end='\n\n')
print("Array of random matrix : '\n'",ra_f,end='\n\n')
print("Array of random numeric matrix : '\n'",ra_m,end='\n\n')
print("Array of random choise form list : '\n'",ra_choice,end='\n\n')
print("Array Shape : '\n'",arr3.shape,end='\n\n')
print("Array ReShape : '\n'",reshape.shape,end='\n\n')
print("flattening an Array  : ",flatten,end='\n\n')
print("Transformed an Array  : ",trnasform,end='\n\n')

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[['vamsi' 'vamsi' 'vamsi' 'vamsi']
 ['vamsi' 'vamsi' 'vamsi' 'vamsi']
 ['vamsi' 'vamsi' 'vamsi' 'vamsi']
 ['vamsi' 'vamsi' 'vamsi' 'vamsi']]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of Even numbers :  [ 0  2  4  6  8 10]

Array of 2 parts :  [ 1.  25.5 50. ]

Array of random number :  105562

Array of random matrix : '
' [[0.55286193 0.97825407 0.40888936 0.76503639 0.54284372]
 [0.93599465 0.80123347 0.8373421  0.11939348 0.66176563]
 [0.10743533 0.90152891 0.45050184 0.78140802 0.22753837]
 [0.40356345 0.56954826 0.90897083 0.68253628 0.60820756]
 [0.52124979 0.17631396 0.40053617 0.93360919 0.51937283]]

Array of random numeric matrix : '
' [[18 47]
 [11 49]]

Array of random choise form list : '
' ['ramya' 'ramya']

Array Shape : '
' (3, 6)

Array ReShape : '
' (6, 3)

flattening an Array  :  [1 2 3 4 5 6 1 2 1 1 2 1 1 2 1 1 2 1]

T

In [ ]:
print(arr3)
print(arr3[0:4,2:4])
print(arr3+1)
print(arr3*1)
print(arr3**2)
print(np.sqrt(arr3),'\n')
print(np.log(arr3),'\n')
print(np.sin(arr3),'\n')
print(np.cos(arr3),'\n')
print(np.sum(arr3),'\n')
print(np.median(arr3),'\n')
print(np.mean(arr3),'\n')
print("Variance : ",np.var(arr3),'\n')
print("maximum element :",np.max(arr3),'\n')
print("Minimum element :",np.min(arr3),'\n')
print("Cummulative Sum '\n' :",np.cumsum(arr3),'\n')
print("Cummulative Product '\n':",np.cumprod(arr3),'\n')
print("Greater the 4 '\n':",arr3>4,'\n')
print("Sorting the elements'\n':",np.sort(arr3),'\n')
print("Unique the elements'\n':",np.unique(arr3),'\n')

[[1 2 3 4 5 6]
 [1 2 1 1 2 1]
 [1 2 1 1 2 1]]
[[3 4]
 [1 1]
 [1 1]]
[[2 3 4 5 6 7]
 [2 3 2 2 3 2]
 [2 3 2 2 3 2]]
[[1 2 3 4 5 6]
 [1 2 1 1 2 1]
 [1 2 1 1 2 1]]
[[ 1  4  9 16 25 36]
 [ 1  4  1  1  4  1]
 [ 1  4  1  1  4  1]]
[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
 [1.         1.41421356 1.         1.         1.41421356 1.        ]
 [1.         1.41421356 1.         1.         1.41421356 1.        ]] 

[[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
 [0.         0.69314718 0.         0.         0.69314718 0.        ]
 [0.         0.69314718 0.         0.         0.69314718 0.        ]] 

[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.84147098  0.90929743  0.84147098  0.84147098  0.90929743  0.84147098]
 [ 0.84147098  0.90929743  0.84147098  0.84147098  0.90929743  0.84147098]] 

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
 [ 0.54030231 -0.41614684  0.54030231  0.54030231 -0.